packages:
  - apps/*
  - packages/*
  - packages/configs/*

catalog:
  '@playwright/test': 1.58.0
  '@rsbuild/core': 1.7.2
  '@rsbuild/plugin-react': 1.4.3
  '@rspack/core': 1.7.3
  '@tanstack/react-table': 8.21.3,
  '@testing-library/react': 16.3.2
  '@testing-library/user-event': 14.6.1
  '@types/node': 24.10.4
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  '@vitest/coverage-v8': 4.0.18
  eslint: 9.39.2
  react: 19.2.4
  react-dom: 19.2.4
  storybook: 10.2.0
  tailwindcss: 4.1.18
  'tw-animate-css': 1.4.0
  typescript: 5.9.3
  non.geist: 2.0.1
  vitest: 4.0.18
