// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%WOQOPOOOcOQO'#C_OhOQO'#CcOOOO'#C^'#C^QmOPOOOrOQO,58yOwOSO,58}Q|OWO'#ClQmOPOOO![OQO1G.eO!gOQO1G.iO!rOWO'#CgO!}O`O'#CgO#YOWO'#CjOOOO,59W,59WQ#hOpOOQ#mOPOOOOOO-E6j-E6jO#rOPO7+$PO#}O!bO7+$TO$YO`O,59ROOOO,59R,59RO$eOWO,59RQOOOOOP$pOWO'#ClO${OQO<<GkOOOO<<Go<<GoOOOO1G.m1G.mO%WO`O1G.mP%cOWO'#CgOOOOAN=VAN=VOOOO7+$X7+$X",
  stateData: "%q~OSPOUQOYROaQPcQP~ObTO~ObUO~OcVO~OTXO~OWYO~O[ZOc_Od]Oe[O~ObbOaRicRi~ObcOaVicVi~OedOaZXcZX~O]eOaZXcZX~O[fOedOa^Xc^X~O_gO~Oc_O~OUiOaRqcRq~OXjOaVqcVq~O]kOaZacZa~OelOaZacZa~O[ZOdmOe[O~ObnOaRycRy~O]oOaZicZi~O[fOedO~OUSd[Y~",
  goto: "uaPPbePPPePPPhPPlPoRSORROT^VhR`VQWSRaW",
  nodeNames: "⚠ Message StartLine RequestLine Method Target Version StatusLine StatusCode ReasonPhrase StartLineText Header HeaderName HeaderValue BlankLine Body",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "2b#sR^OX}XY&TYZ'UZp}pq&Tq![}![!]'f!]!c}!c!j(a!j!k)v!k!}(a!};'S};'S;=`%}<%lO}#s!`Y_p]`X!bWSTQ[WYPOX}XY#OYZ#rZp}pq#Oq![}![!]%O!];'S};'S;=`%}<%lO}#m#]V_p]`X!b[WYPOY#OYZ#rZ![#O![!]$W!];'S#O;'S;=`$x<%lO#Op#wR_pO;'S#r;'S;=`$Q<%lO#rp$TP;=`<%l#r#e$cT_p]`X!bYPOY$WYZ#rZ;'S$W;'S;=`$r<%lO$W#e$uP;=`<%l$W#m${P;=`<%l#O#k%_W_p]`X!bWSTQYPOX%OXY$WYZ#rZp%Opq$Wq;'S%O;'S;=`%w<%lO%O#k%zP;=`<%l%O#s&QP;=`<%l}#o&fY_p]`X!bbQdW[WYPOX#OXY&TYZ#rZp#Opq&Tq![#O![!]$W!];'S#O;'S;=`$x<%lO#O#o']R_pc!}O;'S#r;'S;=`$Q<%lO#r#s'wWeW_p]`X!bWSTQYPOX%OXY$WYZ#rZp%Opq$Wq;'S%O;'S;=`%w<%lO%O#s(t`_p]`X!bWSTQSP[WYPOX}XY#OYZ#rZp}pq#Oq}}}!O(a!O![}![!]%O!]!c}!c!}(a!}#R}#R#S(a#S;'S};'S;=`%}<%lO}#s*Zb_p]`X!bWSTQSP[WYPOX}XY#OYZ#rZp}pq#Oq}}}!O(a!O![}![!]%O!]!c}!c!v(a!v!w+c!w!}(a!}#R}#R#S(a#S;'S};'S;=`%}<%lO}#s+vb_p]`X!bWSTQSP[WYPOX}XY#OYZ#rZp}pq#Oq}}}!O(a!O![}![!]%O!]!c}!c!v(a!v!w-O!w!}(a!}#R}#R#S(a#S;'S};'S;=`%}<%lO}#s-cb_p]`X!bWSTQSP[WYPOX}XY#OYZ#rZp}pq#Oq}}}!O(a!O![}![!]%O!]!c}!c!r(a!r!s.k!s!}(a!}#R}#R#S(a#S;'S};'S;=`%}<%lO}#s/Ob_p]`X!bWSTQSP[WYPOX}XY#OYZ#rZp}pq#Oq}}}!O(a!O!P}!P!Q0W!Q![}![!]%O!]!c}!c!}(a!}#R}#R#S(a#S;'S};'S;=`%}<%lO}#s0kY_p]`X!bWSTQUP[WYPOX0WXY#OYZ#rZp0Wpq#Oq![0W![!]1Z!];'S0W;'S;=`2[<%lO0W#k1lW_p]`X!bWSTQUPYPOX1ZXY$WYZ#rZp1Zpq$Wq;'S1Z;'S;=`2U<%lO1Z#k2XP;=`<%l1Z#s2_P;=`<%l0W",
  tokenizers: [0, 1, 2, 3, 4, 5, 6],
  topRules: {"Message":[0,1]},
  tokenPrec: 211
})
