// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Message = 1,
  StartLine = 2,
  RequestLine = 3,
  Method = 4,
  Target = 5,
  Version = 6,
  StatusLine = 7,
  StatusCode = 8,
  ReasonPhrase = 9,
  StartLineText = 10,
  Header = 11,
  HeaderName = 12,
  HeaderValue = 13,
  BlankLine = 14,
  Body = 15
